before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep libotr -y
language: c
compiler:
  - clang
  - gcc
script: autoreconf -s -i && ./configure --with-pic --prefix=/usr --mandir=/usr/share/man && make 
